### ISSUE TITLE
Can't load models in a Flink Cluster setup

### ISSUE THREAD

**Issue by Harish-Sridhar** [radicalbit/flink-jpmml#64]
Hi,

I built a sample flink application that consumes events from Kafka Topic and evaluates the incoming events using a model present in the file system using `ModelReader`

```
val prediction = appsDataStream.evaluate(modelReader) {
      //Iris data and modelReader instance
      case (event, model) =>
        val vectorized = event.toDenseVector
        val prediction = model.predict(vectorized, Some(0.0))

        (event, prediction)
    }
```

This works on a flink local cluster. However this doesn't work when I deploy the applicatoin on a flink cluster with job manager and task manager running in separate nodes. 

The reason for this not working is the PMML model along with application is packaged as a fat jar and uploaded to the job manager. The Job manager sends model evaluate task to the task managers and the task managers don't have the PMML model file available.

Currently `flink-jpmml` implementation only allows the path of the pmml model file to be provided as input and the library implements the model upload using the path. This doesn't work in cluster mode.
We may need additional implementation where by we can provide the whole PMML model file InputStream using which the library can upload the PMML models.

Regards,
Harish.

**Comment by spi-x-i** [comment]
Dear Harish-Sridhar, thank you for your recent activity on this project.

Actually, `flink-jpmml` aims to serve models stored to the Flink underlying storage system. We've been made several tests with HDFS, Alluxio and even local FS. Even more, I'd suggest that TaskManager's do actually have the ability to access the FS directly w/o relying on the JobManager.

I guess your issue is that you're running in _cluster-mode_ without relying on a distributed underlying FileSystem; this causes your TMs trying to access a local path which is not available in the machine (because is local in fact). Thus, I suggest you adopt a [distributed filesystem](https://ci.apache.org/projects/flink/flink-docs-stable/ops/filesystems.html) approach if you run with a cluster.

Please, also note that you're using old APIs. 
In later releases, `flink-jpmml` is now able to load dynamically PMML models by connecting an event stream with a control stream which provides the models' metadata. Take a look at the `README.md` file to grasp this concept better.

Hope it helps, I'm closing this issue because we can't identify any changes needed here.

**Comment by spi-x-i** [comment]
Closing the issue because we can't identify any changes needed here.
